- name: Install required system packages
  apt:
    name:
      - ca-certificates
      - gnupg
      - lsb-release
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker’s official GPG key
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install