---
- name: Install common apt packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - git
      - curl
      - jq
      - wget
      - tree
      - unzip
      - make
      - gcc
      - software-properties-common
      - python3
      - python3-dev
      - python3-pip
    state: present
    install_recommends: no
    update_cache: yes